### ISSUE TITLE
check_zpool_scrub: Illegal number:      0B repaired, 45.26% done, 0 days 01:07:10 to go

### ISSUE THREAD

**Issue by FloMiau** [Josef-Friedrich/check_zpool_scrub#11]
Hey there,

I recently upgraded to Debian Buster.

Now I get the following error while scrubbing

```
/usr/lib/nagios/plugins/check_zpool_scrub
/usr/lib/nagios/plugins/check_zpool_scrub: 494: /usr/lib/nagios/plugins/check_zpool_scrub: Illegal number:      0B repaired, 45.26% done, 0 days 01:07:10 to go
OK: The last scrub on zpool 'zfsdata' was performed on 2019-08-03.10:21:02. | warning=2678400 critical=5356800 zfsdata_last_ago=3333 zfsdata_progress=100 zfsdata_speed=133 9 zfsdata_time=
```

The output of `zpool status` is:

```
  pool: zfsdata
 state: ONLINE
  scan: scrub in progress since Sat Aug  3 10:21:02 2019
        461G scanned at 120M/s, 258G issued at 67.2M/s, 496G total
        0B repaired, 52.05% done, 0 days 01:00:21 to go
config:

        NAME                                       STATE     READ WRITE CKSUM
        zfsdata                                    ONLINE       0     0     0
          mirror-0                                ONLINE       0     0     0
            ata-SanDisk_SDSSD            ONLINE       0     0     0  (trimming)
            ata-SanDisk_SDSSD            ONLINE       0     0     0  (trimming)

errors: No known data errors


```

It looks like that there is a new field "days" which confuses the monitoring.

**Comment by Josef-Friedrich** [comment]
Thank you for reporting. Would you be so kind an test  eaae2f8

**Comment by taam** [comment]
This issue is not solved I think, I'm getting the same error. It's probably not the progress functions that fail, but the time functions, in particular this regex:

https://github.com/Josef-Friedrich/check_zpool_scrub/blob/60a260efab2eab80915cf9177754da2b19c81704/check_zpool_scrub#L487

**Comment by Josef-Friedrich** [comment]
@taam Thank you for your report. Could you please specify the output of `zpool status` that causes your described problem.

**Comment by taam** [comment]
Sure, but it's very similar to the one above:

```
  pool: xxx
 state: ONLINE
  scan: scrub in progress since Thu May 20 00:18:06 2021
        287G scanned at 962M/s, 31,3G issued at 105M/s, 2,70T total
        0B repaired, 1,13% done, 0 days 07:25:04 to go
config:

        NAME                                          STATE     READ WRITE CKSUM
        xxx                                           ONLINE       0     0     0
          mirror-0                                    ONLINE       0     0     0
            ata-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ONLINE       0     0     0
            ata-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ONLINE       0     0     0

errors: No known data errors
```

(I've also seen variants with the ISO time but without the "x days", but don't know what version/system that was from.)

**Comment by Josef-Friedrich** [comment]
@taam could you please test 6e23e5ca54384cff75fcc0133081735f914e5208. Hopefully the problem is solved now.

**Comment by taam** [comment]
Works for me (but comment regarding indentation applies: https://github.com/Josef-Friedrich/check_zpool_scrub/issues/12#issuecomment-850795202).

However, seems OpenZFS 2.0 changes the output again (with https://github.com/openzfs/zfs/commit/9a49d3f3d3bfa26df4e5e54d574cb490f0ee284b), the current string can be without "x days" as mentioned, see:

https://github.com/openzfs/zfs/blob/a1ca39655ba446c98a2f44b2b1d45d1059738885/cmd/zpool/zpool_main.c#L7400-L7408
