### ISSUE TITLE
zpool status should not be called multiple times (per pool)

### ISSUE THREAD

**Issue by taam** [Josef-Friedrich/check_zpool_scrub#12]
Currently `zpool status` seems to be called multiple times (per pool) if a scrub is running, which would probably be bad for various reasons (consistency, debugging/testing, performance).

**Comment by Josef-Friedrich** [comment]
Thank you for pointing this out. One solution could be to store the output of `zpool status` in a variable. PR are very welcome!

**Comment by Josef-Friedrich** [comment]
@taam Could you please test the latest version. `zpool status` should now be called only once.

**Comment by taam** [comment]
There are still 3 places where it could be called it seems (`_last_scrub_grab_ctime_from_command`, `_get_zpool_status_stdout`, `_check_one_pool`), but the else case of `_get_zpool_status_stdout` is probably never reached? This `else` is also a bit inconsistent in that it does not update `ZPOOL_STATUS_EXIT_CODE`.

I have basically no experience in shell scripting, so the following could be very wrong. With the current order, one pool after another, a cleaner way to me seems to remove the 3 new global variable, but prepend `local ` to the calls in `_check_one_pool`, so that they are visible until this function returns. The `_get_zpool_status_stdout` `else` then just needs to fail. (For a really caching get function a map would be nice, but that's not easily available with pure shell as far as I know.)

Unfortunately these last commits have formatting issues, adding lots of inconsistent indentation. (The code had tab indentation, so it probably should stay that way.)

**Comment by Josef-Friedrich** [comment]
Thank you for your thorough review.
