### ISSUE TITLE
Performance data format/limits

### ISSUE THREAD

**Issue by taam** [Josef-Friedrich/check_zpool_scrub#13]
Currently the limits (warning/critical) are emitted as separate performance data items, e.g.: `warning=2678400 critical=5356800` Maybe there is some system, that requires that, but it seems wrong as these limits are only relevant for the `*_last_ago` items. (Also consider possible future improvements like pool specific limits.)

The correct units and these limits should be added in the appropriate format (see e.g. https://nagios-plugins.org/doc/guidelines.html#AEN200) to the relevant values themselves. The separate limit items should probably be removed unless required for something else.

(Btw. thanks for the latest changes, it seems to be more stable now.)

**Comment by Josef-Friedrich** [comment]
Thank you for your report. Could you please review the last change.

**Comment by taam** [comment]
Looking good, thanks! I think the units also should be used, this allows the consumer to show the numbers with scaled units appropriately, e.g. Icinga (Web) does this and shows the age in hours/days/..., which is a lot better to read. I've created a pull request for that, feel free to rewrite as you want: #14

In case you do not want to change the time to go unit, one could still use part of the other commit (the one with the units).
