### ISSUE TITLE
Time to go calculation broken for some numbers

### ISSUE THREAD

**Issue by taam** [Josef-Friedrich/check_zpool_scrub#15]
The arithmetic expression for calculating the time to go while scrubbing is broken, as some sh implementations (can) interpret numbers with leading zeros as octal numbers. This can easily happen with two digits hours, minutes and seconds, resulting in error messages like `Illegal number: 08` or `09`.

https://github.com/Josef-Friedrich/check_zpool_scrub/blob/df24487bfad11455dda48cd0fac42fd6b7b935b4/check_zpool_scrub#L443

A quick/dirty/bad hack would be to remove a single potential leading 0 for these only. I was looking for a clean sh only solution (removing an arbitrary number of leading zeros, but keep the last one if the string is zeros only) but did not find a good one. :(

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this. Can you please review 9fc9373f455a0e4980d87e936e2036c6041addf0.

**Comment by taam** [comment]
Seems to work (for me), thanks!

(Some side note: I must admit that it also seems pretty painful. For testing I installed some other sh implementations, from what I've seen the script actually works only with bash and dash anyway. `SECONDS` is actually a builtin variable in bash, but it seems ok due to the (non-standard?) `local`. Other typical system scripting languages like Perl and Python also have their ugly sides for sure, but sh somehow seems just that, even more painful when doing more than just running some commands. This is not supposed to be a rant, it's just interesting for me that what previously was more like a feeling is getting verified as I look deeper into it.)
