### ISSUE TITLE
if --pool not provided, run on all pools

### ISSUE THREAD

**Issue by dlangille** [Josef-Friedrich/check_zpool_scrub#4]
I have a suggestion, but not complete code.

If you have multiple pools, just one pool, or add pools later, it is more convenient to have a script which always keeps up.

Suggestion: if -p is not specified do something like this:

```
#/bin/sh

pools=`zpool list -H -o name`
for pool in ${pools}
do
  echo do a scrub check on that $pool
done
```

The above can be invoked inside the existing code.

Sample output:

```
[dan@slocum:~/src/check_zpool_scrub] $ sh ~/bin/zpools.sh
do a scrub check on that dev-ingress01
do a scrub check on that jester
do a scrub check on that system
do a scrub check on that tank_fast
```

Does this sound OK to you?

**Comment by Josef-Friedrich** [comment]
Sounds OK! PR?

**Comment by dlangille** [comment]
After giving it some thought, it's as if I would use check_zpool_scrub as a separate script, and invoke it from a script which looks like the above.  Let me ponder a bit longer.

**Comment by dlangille** [comment]
How about this?

[check_zpool_scrub.txt](https://github.com/Josef-Friedrich/check_zpool_scrub/files/2288319/check_zpool_scrub.txt)

**Comment by Josef-Friedrich** [comment]
Very nice!

```sh
#!/bin/sh

OUTPUT=""
STATE=0

# sort in reverse order, because we append in that order
pools=`zpool list -H -o name | sort -r`
for pool in ${pools}
do
  OUTPUT="$OUTPUT `check_zpool_scrub --pool=$pool --warning=777600 --critical=1209600`"
  LAST_STATE=$?
  if [ ${LAST_STATE} -gt ${STATE} ]
  then
    STATE=${LAST_STATE}
  fi

done

echo $OUTPUT
exit ${STATE}
```

**Comment by Josef-Friedrich** [comment]
5f931c0828187cf3d4fd4e3ca2b6028b70558db6
